# 基础镜像
FROM nginx
# author
MAINTAINER yjj

# 挂载目录
VOLUME /home/yjj/projects/yjj-ui
# 创建目录
RUN mkdir -p /home/yjj/projects/yjj-ui
# 指定路径
WORKDIR /home/yjj/projects/yjj-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/yjj/projects/yjj-ui
